# Generated by Django 5.1.7 on 2025-06-11 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название продукта')),
                ('model', models.CharField(blank=True, null=True, verbose_name='Модель продукта')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='NetworkElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название звена')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(verbose_name='Страна')),
                ('city', models.CharField(verbose_name='Город')),
                ('street', models.CharField(verbose_name='Улица')),
                ('building', models.CharField(verbose_name='Строение')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('debt_to_parent', models.FloatField(blank=True, default=0, null=True, verbose_name=2)),
                ('network_lvl', models.IntegerField(blank=True, default=0, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='sales_network.networkelement')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales_network.product')),
            ],
            options={
                'verbose_name': 'Звено сети',
                'verbose_name_plural': 'Звенья сети',
            },
        ),
    ]
