# Generated by Django 5.1.7 on 2025-06-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkelement',
            name='products',
        ),
        migrations.AddField(
            model_name='networkelement',
            name='products',
            field=models.ManyToManyField(to='sales_network.product'),
        ),
    ]
