# Generated by Django 5.1.7 on 2025-06-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0002_remove_networkelement_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkelement',
            name='products',
            field=models.ManyToManyField(related_name='product', to='sales_network.product'),
        ),
    ]
