# Generated by Django 5.1.7 on 2025-06-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0003_alter_networkelement_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkelement',
            name='debt_to_parent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
